use [DATABASE_PLACEHOLDER]
GO

--- This Script (T-SQL Batch Statements)
--- Creates Appropriate Relationships
--- Between all the tables contained in
--- the [DATABASE_PLACEHOLDER] Database

--- Creation of Primary Keys

ALTER TABLE [Administrators].[Info] ADD CONSTRAINT pkADMIN_INFO PRIMARY KEY (AdministratorID)
GO

ALTER TABLE [Administrators].[Note] ADD CONSTRAINT pkADMIN_NOTE PRIMARY KEY (NoteID)
GO

ALTER TABLE [Administrators].[Profile] ADD CONSTRAINT pkADMIN_PROFILE PRIMARY KEY (ProfileID)
GO

ALTER TABLE [Faculties].[Info] ADD CONSTRAINT pkFAC_INFO PRIMARY KEY (FacultyID)
GO

ALTER TABLE [Faculties].[Note] ADD CONSTRAINT pkFAC_NOTE PRIMARY KEY (NoteID)
GO

ALTER TABLE [Faculties].[Profile] ADD CONSTRAINT pkFAC_PROFILE PRIMARY KEY (ProfileID)
GO

ALTER TABLE [Faculties].[Subject] ADD CONSTRAINT pkFAC_SUBJECT PRIMARY KEY (SubjectID)
GO

ALTER TABLE [General].[Course] ADD CONSTRAINT pkGEN_COURSE PRIMARY KEY (CourseID)
GO

ALTER TABLE [General].[Relations] ADD CONSTRAINT pkGEN_RELATIONS PRIMARY KEY (RelationsID)
GO

ALTER TABLE [General].[Semester] ADD CONSTRAINT pkGEN_SEMESTER PRIMARY KEY (SemesterID)
GO

ALTER TABLE [General].[Subject] ADD CONSTRAINT pkGEN_SUBJECT PRIMARY KEY (SubjectID)
GO

ALTER TABLE [Shared].[Announcement] ADD CONSTRAINT pkSHA_ANNOUNCEMENT PRIMARY KEY (AnnouncementID)
GO

ALTER TABLE [Shared].[AnswerForum] ADD CONSTRAINT pkSHA_ANSWERFORUM PRIMARY KEY (AnswerID)
GO

ALTER TABLE [Shared].[QuestionForum] ADD CONSTRAINT pkSHA_QUESTIONFORUM PRIMARY KEY (QuestionID)
GO

ALTER TABLE [Shared].[Note] ADD CONSTRAINT pkSHA_NOTE PRIMARY KEY (NoteID)
GO

ALTER TABLE [Shared].[Message] ADD CONSTRAINT pkSHA_MESSAGE PRIMARY KEY (MessageID)
GO

ALTER TABLE [Students].[Course] ADD CONSTRAINT pkSTU_COURSE PRIMARY KEY (CourseID)
GO

ALTER TABLE [Students].[Note] ADD CONSTRAINT pkSTU_NOTE PRIMARY KEY (NoteID)
GO

ALTER TABLE [Students].[Profile] ADD CONSTRAINT pkSTU_PROFILE PRIMARY KEY (ProfileID)
GO

ALTER TABLE [Students].[Semester] ADD CONSTRAINT pkSTU_SEMESTER PRIMARY KEY (SemesterID)
GO

ALTER TABLE [Students].[Info] ADD CONSTRAINT pkSTU_INFO PRIMARY KEY (StudentID)
GO

ALTER TABLE [Auth].[Student] ADD CONSTRAINT pkAUTH_STUDENT PRIMARY KEY (LoginID)
GO

ALTER TABLE [Auth].[Faculty] ADD CONSTRAINT pkAUTH_FACULTY PRIMARY KEY (LoginID)
GO

ALTER TABLE [Auth].[Administrator] ADD CONSTRAINT pkAUTH_ADMINISTRATOR PRIMARY KEY (LoginID)
GO

ALTER TABLE [Auth].[LoginMeta] ADD CONSTRAINT pkAUTH_LOGINMETA PRIMARY KEY (MetaID)
GO

ALTER TABLE [Students].[Account] ADD CONSTRAINT pkSTUDENT_ACCOUNT PRIMARY KEY (AccountID)
GO

ALTER TABLE [Faculties].[Account] ADD CONSTRAINT pkFACULTY_ACCOUNT PRIMARY KEY (AccountID)
GO

ALTER TABLE [Administrators].[Account] ADD CONSTRAINT pkADMINISTRATOR_ACCOUNT PRIMARY KEY (AccountID)
GO

ALTER TABLE [Shared].[MessageContent] ADD CONSTRAINT pkSHARED_MESSAGECONTENT PRIMARY KEY (MessageContentID)
GO



--- Creation of Foreign Keys

ALTER TABLE [Administrators].[Note] ADD CONSTRAINT fkADMIN_NOTE
FOREIGN KEY (Administrator) REFERENCES [Administrators].[Info] (AdministratorID)
ON UPDATE CASCADE ON DELETE CASCADE
GO

ALTER TABLE [Administrators].[Profile] ADD CONSTRAINT fkADMIN_PROFILE
FOREIGN KEY (Administrator) REFERENCES [Administrators].[Info] (AdministratorID)
ON UPDATE CASCADE ON DELETE CASCADE
GO

ALTER TABLE [Faculties].[Note] ADD CONSTRAINT fkFAC_NOTE
FOREIGN KEY (Faculty) REFERENCES [Faculties].[Info] (FacultyID)
ON UPDATE CASCADE ON DELETE CASCADE
GO

ALTER TABLE [Faculties].[Profile] ADD CONSTRAINT fkFAC_PROFILE
FOREIGN KEY (Faculty) REFERENCES [Faculties].[Info] (FacultyID)
ON UPDATE CASCADE ON DELETE CASCADE
GO

ALTER TABLE [Faculties].[Subject] ADD CONSTRAINT fkFAC_SUBJECTFAC
FOREIGN KEY (Faculty) REFERENCES [Faculties].[Info] (FacultyID)
ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT fkFAC_COURSEGEN FOREIGN KEY (Course) REFERENCES [General].[Course] (CourseID)
ON UPDATE CASCADE ON DELETE SET NULL,
CONSTRAINT fkFAC_SEMESTERGEN FOREIGN KEY (Semester) REFERENCES [General].[Semester] (SemesterID)
ON UPDATE CASCADE ON DELETE SET NULL,
CONSTRAINT fkFAC_SUBJECTGEN FOREIGN KEY (Subject) REFERENCES [General].[Subject] (SubjectID)
ON UPDATE CASCADE ON DELETE CASCADE
GO

ALTER TABLE [Shared].[Announcement] ADD CONSTRAINT fkSHA_ANNOUNCERFROM
FOREIGN KEY (AnnouncerFrom) REFERENCES [General].[Relations] (RelationsID),
CONSTRAINT fkSHA_ANNOUNCERTO FOREIGN KEY (AnnouncerTo) REFERENCES [General].[Relations] (RelationsID)
GO

ALTER TABLE [Shared].[AnswerForum] ADD CONSTRAINT fkSHA_ANSWERFORUM
FOREIGN KEY (AnsweredByType) REFERENCES [General].[Relations] (RelationsID)
ON UPDATE CASCADE ON DELETE CASCADE
GO

ALTER TABLE [Shared].[QuestionForum] ADD CONSTRAINT fkSHA_QUESTIONFORUM
FOREIGN KEY (AskedBy) REFERENCES [Students].[Info] (StudentID)
ON UPDATE CASCADE ON DELETE SET NULL
GO
 
ALTER TABLE [Shared].[Message] ADD CONSTRAINT fkSHA_MESSAGEFROM
FOREIGN KEY (MessageFromType) REFERENCES [General].[Relations] (RelationsID),
CONSTRAINT fkSHA_MESSAGETO FOREIGN KEY (MessageToType) REFERENCES [General].[Relations] (RelationsID)
GO

ALTER TABLE [Shared].[Note] ADD CONSTRAINT fkSHA_NOTEFROM
FOREIGN KEY (NoteFromType) REFERENCES [General].[Relations] (RelationsID),
CONSTRAINT fkSHA_NOTETO FOREIGN KEY (NoteToType) REFERENCES [General].[Relations] (RelationsID)
GO

ALTER TABLE [Students].[Course] ADD CONSTRAINT fkSTU_COURSE
FOREIGN KEY (Course) REFERENCES [General].[Course] (CourseID)
ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT fkSTU_STUDENT FOREIGN KEY (Student) REFERENCES [Students].[Info] (StudentID)
ON UPDATE CASCADE ON DELETE CASCADE
GO

ALTER TABLE [Students].[Note] ADD CONSTRAINT fkSTU_NOTE
FOREIGN KEY (Student) REFERENCES [Students].[Info] (StudentID)
ON UPDATE CASCADE ON DELETE CASCADE
GO

ALTER TABLE [Students].[Profile] ADD CONSTRAINT fkSTU_PROFILE
FOREIGN KEY (Student) REFERENCES [Students].[Info] (StudentID)
ON UPDATE CASCADE ON DELETE CASCADE
GO

ALTER TABLE [Students].[Semester] ADD CONSTRAINT fkSTU_SEMESTER
FOREIGN KEY (Student) REFERENCES [Students].[Info] (StudentID)
ON UPDATE CASCADE ON DELETE CASCADE
GO

ALTER TABLE [Auth].[Student] ADD CONSTRAINT fkAUTH_STUDENT
FOREIGN KEY (Student) REFERENCES [Students].[Info] (StudentID)
ON UPDATE CASCADE ON DELETE CASCADE
GO

ALTER TABLE [Auth].[Faculty] ADD CONSTRAINT fkAUTH_FACULTY
FOREIGN KEY (Faculty) REFERENCES [Faculties].[Info] (FacultyID)
ON UPDATE CASCADE ON DELETE CASCADE
GO

ALTER TABLE [Auth].[Administrator] ADD CONSTRAINT fkAUTH_ADMINISTRATOR
FOREIGN KEY (Administrator) REFERENCES [Administrators].[Info] (AdministratorID)
ON UPDATE CASCADE ON DELETE CASCADE
GO

ALTER TABLE [Auth].[LoginMeta] ADD CONSTRAINT fkAUTH_LOGINMETA
FOREIGN KEY (UserType) REFERENCES [General].[Relations] (RelationsID)
GO

ALTER TABLE [Students].[Account] ADD CONSTRAINT fkSTUDENT_ACCOUNT
FOREIGN KEY (Student) REFERENCES [Students].[Info] (StudentID)
GO

ALTER TABLE [Faculties].[Account] ADD CONSTRAINT fkFACULTY_ACCOUNT
FOREIGN KEY (Faculty) REFERENCES [Faculties].[Info] (FacultyID)
GO

ALTER TABLE [Administrators].[Account] ADD CONSTRAINT fkADMINISTRATOR_ACCOUNT
FOREIGN KEY (Administrator) REFERENCES [Administrators].[Info] (AdministratorID)
GO

ALTER TABLE [Shared].[MessageContent] ADD CONSTRAINT fkSHARED_MESSAGECONTENT
FOREIGN KEY (Message) REFERENCES [Shared].[Message] (MessageID)
GO